// <auto-generated />
using System;
using AppProjetSessionDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppProjetSessionDB.Migrations
{
    [DbContext(typeof(H22_4D5_Projet_sessionContext))]
    partial class H22_4D5_Projet_sessionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppProjetSessionDB.Models.Disponibilite", b =>
                {
                    b.Property<int>("DisponibiliteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("disponibiliteID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateDisponibilite")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateDisponibilite");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time")
                        .HasColumnName("heureDebut");

                    b.Property<int>("PhotographeId")
                        .HasColumnType("int")
                        .HasColumnName("photographeID");

                    b.Property<int?>("RendezVousId")
                        .HasColumnType("int")
                        .HasColumnName("rendezVousID");

                    b.Property<string>("Statut")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("statut");

                    b.HasKey("DisponibiliteId");

                    b.HasIndex(new[] { "RendezVousId" }, "IX_dispo_rdvID");

                    b.HasIndex(new[] { "PhotographeId", "DateDisponibilite", "HeureDebut" }, "UC_photographe_date_heure")
                        .IsUnique();

                    b.ToTable("Disponibilite", "Disponibilites");
                });

            modelBuilder.Entity("AppProjetSessionDB.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("photoID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<int>("RendezVousId")
                        .HasColumnType("int")
                        .HasColumnName("rendezVousID");

                    b.HasKey("PhotoId");

                    b.HasIndex(new[] { "RendezVousId" }, "IX_Photo_RendezVousID");

                    b.ToTable("Photo", "Photos");
                });

            modelBuilder.Entity("AppProjetSessionDB.Models.Photographe", b =>
                {
                    b.Property<int>("PhotographeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("photographeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nom");

                    b.HasKey("PhotographeId");

                    b.ToTable("Photographes", "Utilisateurs");
                });

            modelBuilder.Entity("AppProjetSessionDB.Models.Propriete", b =>
                {
                    b.Property<int>("ProprieteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("proprieteID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("adresse");

                    b.Property<string>("NomProprio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nomProprio");

                    b.Property<string>("TelProprio")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("telProprio");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("ville");

                    b.HasKey("ProprieteId");

                    b.ToTable("Propriete", "Proprietes");
                });

            modelBuilder.Entity("AppProjetSessionDB.Models.RendezVou", b =>
                {
                    b.Property<int>("RendezVousId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rendezVousID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Commentaire")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("commentaire");

                    b.Property<string>("CommentairePhotos")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("commentairePhotos");

                    b.Property<DateTime>("DateRendezVous")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateRendezVous");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time")
                        .HasColumnName("heureDebut");

                    b.Property<string>("Justification")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("justification");

                    b.Property<int>("ProprieteId")
                        .HasColumnType("int")
                        .HasColumnName("proprieteID");

                    b.Property<string>("StatutPhoto")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("statutPhoto")
                        .HasDefaultValueSql("('Aucune')");

                    b.HasKey("RendezVousId")
                        .HasName("PK_rendezVousID");

                    b.HasIndex("ProprieteId");

                    b.ToTable("RendezVous", "Disponibilites");
                });

            modelBuilder.Entity("AppProjetSessionDB.Models.Disponibilite", b =>
                {
                    b.HasOne("AppProjetSessionDB.Models.Photographe", "Photographe")
                        .WithMany("Disponibilites")
                        .HasForeignKey("PhotographeId")
                        .HasConstraintName("FK_photographeID")
                        .IsRequired();

                    b.HasOne("AppProjetSessionDB.Models.RendezVou", "RendezVous")
                        .WithMany("Disponibilites")
                        .HasForeignKey("RendezVousId")
                        .HasConstraintName("FK_rendezVousID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Photographe");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("AppProjetSessionDB.Models.Photo", b =>
                {
                    b.HasOne("AppProjetSessionDB.Models.RendezVou", "RendezVous")
                        .WithMany("Photos")
                        .HasForeignKey("RendezVousId")
                        .HasConstraintName("FK_Photo_rendezVousID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("AppProjetSessionDB.Models.RendezVou", b =>
                {
                    b.HasOne("AppProjetSessionDB.Models.Propriete", "Propriete")
                        .WithMany("RendezVous")
                        .HasForeignKey("ProprieteId")
                        .HasConstraintName("FK_proprieteID")
                        .IsRequired();

                    b.Navigation("Propriete");
                });

            modelBuilder.Entity("AppProjetSessionDB.Models.Photographe", b =>
                {
                    b.Navigation("Disponibilites");
                });

            modelBuilder.Entity("AppProjetSessionDB.Models.Propriete", b =>
                {
                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("AppProjetSessionDB.Models.RendezVou", b =>
                {
                    b.Navigation("Disponibilites");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
